### ISSUE TITLE
Check language cookie in order to bypass the auto-detection and auto-loading of the detected locale

### ISSUE THREAD

**Issue by mendrinos** [vluzrmos/laravel-language-detector#11]
Is it possible to check if there is a cookie related to the language stored? (perhaps the name of the cookie could be defined on the config file) and bypass the auto-detection and do an app::setLocale as per the cookie content.

Now I do it manually, on a parent controller:

```
if (Cookie::get('locale')) {

        App::setLocale(Cookie::get('locale'));

}
```

**Comment by vluzrmos** [comment]
@mendrinos could you test that feature?

You have to update the package to in your `composer.json`

```
"vluzrmos/language-detector": "dev-develop"
```

and add the middleware: 

```
\Vluzrmos\LanguageDetector\Middleware\InjectLanguageCookie::class
```

to your `$middlewares` array on `app/Http/Kernel.php`.

**Comment by mendrinos** [comment]
@vluzrmos 

Looks like you have to decrypt the cookie's contents.

I am getting an error when trying to load the defined locale for another package:

```
Jenssegers\Date\Date::setLocale(): Failed opening required '/home/vagrant/Development/engine/vendor/jenssegers/date/src/Lang/eyJpdiI6IjJEUzNRRHBzeVdmakxhUDZubTFDS0E9PSIsInZhbHVlIjoiRlNESlQ0WmhEM25iaFBSWU9mN0E1dz09IiwibWFjIjoiNTIyMTFiN2ZiYjgxMmMyNTE3YjBiZjFkZTg5Y2I5Njg5ZjJiN2IwOTdlMTg2ZDBmNGM0MTM3MDg1OWIxMTMxMCJ9.php
```

So apparently:

eyJpdiI6IjJEUzNRRHBzeVdmakxhUDZubTFDS0E9PSIsInZhbHVlIjoiRlNESlQ0WmhEM25iaFBSWU9mN0E1dz09IiwibWFjIjoiNTIyMTFiN2ZiYjgxMmMyNTE3YjBiZjFkZTg5Y2I5Njg5ZjJiN2IwOTdlMTg2ZDBmNGM0MTM3MDg1OWIxMTMxMCJ9

is the encrypted cookie content of the 'locale' cookie.

**Comment by vluzrmos** [comment]
In my tests it looks ok, try to use the $request->cookie('locale') or change name of the cookie in your config/lang-detector.php "cookie_name"

![image](https://cloud.githubusercontent.com/assets/450848/12053201/70eeabdc-aef5-11e5-9653-5b97357ac196.png)

**Comment by mendrinos** [comment]
I have the encryption on.. so for the first page load - you seem to add the cookie and the page loads without an issue - but If I enforce a new cookie content (from my drop down) then I get a FatalErrorException:

<img width="1001" alt="screen shot 2015-12-31 at 12 13 58 am" src="https://cloud.githubusercontent.com/assets/1592441/12053372/7664f644-af53-11e5-872b-538b23cc097d.png">
<img width="978" alt="screen shot 2015-12-31 at 12 14 08 am" src="https://cloud.githubusercontent.com/assets/1592441/12053374/79ab7e9a-af53-11e5-9733-08a2b9faf897.png">

**Comment by vluzrmos** [comment]
I see, you have to add the cookie name to $except array of class

```
\App\Http\Middleware\EncryptCookies
```

like:

![image](https://cloud.githubusercontent.com/assets/450848/12053759/e252fd14-aefa-11e5-84e5-746175be26f7.png)

**Comment by vluzrmos** [comment]
Only if that cookie is used out of illuminate cookie (like in jenssegers/date)

**Comment by vluzrmos** [comment]
@mendrinos that is no longer necessary, you only have to add the middleware InjectLanguageCookie.

I released v1.0.13 with that feature, thanks for suggestion!

**Comment by vluzrmos** [comment]
the middleware InjectLanguageCookie is no longer necessary on v1.0.14, you only need to add the middleware

```
\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class
```

**Comment by mendrinos** [comment]
@vluzrmos 

I have a controller that looks like this:

```
Route::get('language/{language}', function($language)
{   
    return Redirect::back()->withCookie(Cookie::forever('locale', $language));
});
```

But it looks like the new page loads after the redirect overrides the cookie I try to set.

Is the logic of "if cookie exist then just load the locale on that cookie" there?

**Comment by vluzrmos** [comment]
That cookie is queued for the LanguageDetector,  so you have to queue that too:

``` php

Route::get("language/{language}", function($language) {
  cookie()->queue(
    cookie()->forever("locale", $language)
  );

  return redirect()->back();

}) ;

```

**Comment by mendrinos** [comment]
@vluzrmos Thanks!
