### ISSUE TITLE
Undefined method Illuminate\Cookie\Middleware\EncryptCookies::disableFor()

### ISSUE THREAD

**Issue by blitss** [vluzrmos/laravel-language-detector#15]
Whoops, looks like something went wrong.

1/1
FatalErrorException in LanguageDetectorServiceProvider.php line 93:
Call to undefined method Illuminate\Cookie\Middleware\EncryptCookies::disableFor()
in LanguageDetectorServiceProvider.php line 93

---

**How solve it?**
Laravel 5.0, php 5.6

**Comment by vluzrmos** [comment]
The quickly solution is disabling the cookie feature,

   LANG_DETECTOR_COOKIE=false

Later I will try to find a better solution.
