### ISSUE TITLE
Incompatibility with Laravel 5.4

### ISSUE THREAD

**Issue by hlorofos** [vluzrmos/laravel-language-detector#17]
Here is the error we're getting with Laravel 5.4

Type error: Argument 1 passed to Vluzrmos\LanguageDetector\LanguageDetector::__construct() must be an instance of Symfony\Component\Translation\TranslatorInterface, instance of Illuminate\Translation\Translator given, called in vendor/vluzrmos/language-detector/src/Providers/LanguageDetectorServiceProvider.php on line 172

**Comment by mbardelmeijer** [comment]
PR created for Laravel 5.4 support: #18

**Comment by skarampatakis** [comment]
I have tried the changes you suggested manually but it seems not to be working. It gets stuck on the if statement. Any hint?
