### ISSUE TITLE
Class language.routePrefix does not exist

### ISSUE THREAD

**Issue by ghost** [vluzrmos/laravel-language-detector#25]
How and where I must insert routePrefix ?

**Comment by jellydn** [comment]
Hello, @mrsamirmh Have you fixed this issue yet? I met this error and am wondering how do you fix this? Thank you in advance.

**Comment by ghost** [comment]
I can't remember. It was nearly 2 year ago 😄 But I can suggest you this similar package: [mcamara/laravel-localization](https://github.com/mcamara/laravel-localization)

**Comment by jellydn** [comment]
Ok, thanks. Let me take a look.
