### ISSUE TITLE
Detection based on TLD

### ISSUE THREAD

**Issue by stefanbauer** [vluzrmos/laravel-language-detector#4]
It would be very interesting if this cool package could also detected the language based on the TLD. Image you have the domains
- mydomain.fr
- mydomain.es
- mydomain.de
- mydomain.com

Wouldn't it be interesting if someone could create kind of mapping in the .env file like fr => FR, de = de_DE, com => en_US etc.

Or is it already possible with a different segment configuration?

**Comment by vluzrmos** [comment]
I think it already does it for domains with a fixed number of segments, it is not flexible but is usable.

you could put that in your .env file or the equivalent to your config/lang-detector.php

```
LANG_DETECTOR_DRIVER="subdomain"
LANG_DETECTOR_SEGMENT=1 # 1 means the second segment
LANG_DETECTOR_LANGUAGES="en,fr,es,de,com:en"
```

Please, try it and let me know if it works.
