### ISSUE TITLE
App::getLocale() is not rendering the detected locale

### ISSUE THREAD

**Issue by mendrinos** [vluzrmos/laravel-language-detector#9]
Despite the fact the the language file is being loaded from the correct identified locale - when I do use:

App::getLocale()

I always get the default one - not the one that has been loaded and auto-detected. 

Any idea why?

**Comment by vluzrmos** [comment]
Same as #7 , it is because the language detector doesnt set the config('app.locale'), it just set locale for the Translator instance. I'm thinking about a callback feature, that is under development in develop branch.

 Please follow up discussion at #7 pull request.

**Comment by vluzrmos** [comment]
Released 1.0.10 with callbacks feature.

**Comment by mendrinos** [comment]
:+1:
